service: sls-workshop-users

plugins:
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

custom:
  prune:
    automatic: true
    number: 1

functions:
  users:
    handler: functions/user.handler
    memorySize: 128
    environment:
      DB_HOST: sls-workshop-users.cjmgmvbaia9s.us-east-1.rds.amazonaws.com
      DB_USER: root
      DB_PASS: EscaleWorkshop#123
    events:
      - http:
          path: create/
          method: post

resources:
  Resources:
    Database:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 100
        AutoMinorVersionUpgrade: true
        AvailabilityZone: us-east-1a
        DBInstanceClass: db.t2.micro
        DBInstanceIdentifier: ${self:service}
        DBName: slsworkshop
        Engine: mariadb
        EngineVersion: 10.1.34
        MasterUsername: "root"
        MasterUserPassword: EscaleWorkshop#123
        PubliclyAccessible: true
