service: sls-workshop-users

plugins:
  - serverless-offline
  - serverless-prune-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

custom:
  prune:
    automatic: true
    number: 1

